export  const countryContants = {
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',
    SEARCH :'SEARCH',
    GET_COUNTRY_DETAIL_REQUEST: 'GET_COUNTRY_DETAIL_REQUEST',
    GET_COUNTRY_DETAIL_SUCCESS: 'GET_COUNTRY_DETAIL_SUCCESS',
    GET_COUNTRY_DETAIL_FAILURE: 'GET_COUNTRY_DETAIL_FAILURE',
}