export const MONGO_USER = 'tony';
export const MONGO_PASSWORD = 'password';
export const MONGO_DB = 'anyfin';
export const HOST = 'localhost';
export const PORT = '27017';
export const JWT_SECRET = 'We are here to win';
export const FIXER_URL = 'http://data.fixer.io/api/latest';
export const FIXER_ACCESS_TOKEN = 'YOUR_FIXER_ACCESS_TOKEN';
export const URL = 'https://restcountries.eu/rest/v2/';
